### ISSUE TITLE
First Stabilization Checklist

### ISSUE THREAD

**Issue by JLockerman** [timescale/timescaledb-toolkit#107]
Can we stabilize new features for the next release (planned for May 2021):

## Potential features: ##

- [x] [t-digest](https://github.com/timescale/timescale-analytics/issues/1)
- [x] [uddsketch](https://github.com/timescale/timescale-analytics/issues/1)
- [x] [time-weighted average](https://github.com/timescale/timescale-analytics/issues/46)

## Before Stabilization ##

- [x] Check on-disk layout
- [x] Continuous aggregate tests
- [x] Edge case tests
- [x] Benchmark for pathological performance
- [x] Edit Uddsketch on-disk buckets to be delta-encoded varints
- [x] Gather more user feedback
- [x] Audit public APIs for consistency (https://github.com/timescale/timescale-analytics/discussions/113)
- [x] Audit documentation for each type
- [x] Remove experimental schema and markers for each type
- [ ] ~Add stability marker for each type~ Not doing stability-based updates right now
- [ ] ~Add update tests~ rename means this is the first version, add them for the next
- [x] ping docs in https://github.com/orgs/timescale/projects/10

## During Stabilization ##

- [x] move features out of experimental schema
- [x] add features to the stable list
- [x] open PR on new docs repo for features

## Notable Feedback ##

Forthcoming

## Open Questions ##

- [ ] disk-layout tests?

**Comment by JLockerman** [comment]
Which order do we want arguments to be in? Right now we have
```SQL
tdigest(buckets, value)
uddsketch(buckets, error, value)
```

another option is

```SQL
tdigest(value, buckets)
uddsketch(value, buckets, error)
```

**Comment by JLockerman** [comment]
## Function Naming ##

Right now we have a function-per-algorithm, ie.

```SQL
tdigest(buckets, value)
uddsketch(buckets, error, value)
```

another option is to make the algorithm an argument

```SQL
approximate_quantile(value, 'tdigest', buckets)
approximate_quantile(value, 'uddsketch', buckets, error)
```

or 

```SQL
approximate_quantile(value, 'tdigest', '{"buckets": 100}')
approximate_quantile(value, 'uddsketch', '{"buckets": 100, "error":0.10}')
```

or 

```SQL
approximate_quantile(value, NULL::tdigest, buckets)
approximate_quantile(value, NULL::uddsketch, buckets, error)
```

**Comment by JLockerman** [comment]
## Naming Principles ##

### Aliases ###

For functions with a sensible default, it may pay to alias the the algorithm under a more general name. eg. have
```
approxamte_quantile(...)
```
as an alias for
```
tdigest(...)
```

### Descriptive Name ###

It may be useful to have names describe what the function does in addition to what the algorithm is. There are no very good examples in this release, the only one to consider is `tdigest_sketch(...)` for `tdigest(...)`, a better example is `lttb_downsample(...)` instead of `lttb(...)`.

**Comment by JLockerman** [comment]
cc @avthars, @ryanbooz, @mfreed, @cevian. You might be interested in this.

**Comment by JLockerman** [comment]
Downsampling is much easier to unify as `downsample('lttb', value)` since all downsampling returns the same type.

**Comment by davidkohn88** [comment]
the `get_foo` (`get_count`, `get_min` etc) functions for each of these:
a) the name isn't the best
b) in the current documentation, we refer to them in headers/links as `tdigest_foo` or `uddsketch_foo`, which is confusing.

**Comment by davidkohn88** [comment]
We're thinking we want to add a generic `percentile_approx` or similar function before stabilization, at the very least a docs page that gets people pointed in the right direction and gives people where to start if they want to just use an approximate percentile algo and want something that will "do the right thing"

**Comment by JLockerman** [comment]
API discussion is now moved to https://github.com/timescale/timescale-analytics/discussions/113

**Comment by JLockerman** [comment]
# Update 2020/04/20 #

@WireBaron  is currently fuzzing t- digest (PR #118), and uddsketch.

Analysis of the t-digest on-disk layout found nothing of note.  
Analysis of the uddsketch on-disk layout found a potential 10x space improvement (from 2KB to around 300B) by delta-encoding the buckets and storing them in varints. This is a large enough improvement that we will likely change the layout to this before stabilization.
