### ISSUE TITLE
Tracking Issue: CI/CD setup

### ISSUE THREAD

**Issue by JLockerman** [timescale/timescaledb-toolkit#20]
Basic tasks needed for CI/CD:

- [x] Test PG 13 Job: just like [the pg12 job](https://github.com/timescale/timescale-analytics/blob/7f44eeeafe6be0df64aaf92b3bdc19c1e50566d0/.github/workflows/ci.yml#L12-L47) but for pg13
- [x] Update our [pgx image](https://github.com/timescale/timescale-analytics/blob/7f44eeeafe6be0df64aaf92b3bdc19c1e50566d0/docker/Dockerfile) to also include TimescaleDB in the relevant postgres instances (12 and 13?)
- [x] Create dockerfile for building our image
- [x] Set up automatic builds&pushes for our image
- [ ] stretch: only run tests when things under test actually change

**Comment by JLockerman** [comment]
This is basically done
