### ISSUE TITLE
Implement an Approximate Count aggregate using Count-Min Sketch

### ISSUE THREAD

**Issue by rtwalker** [timescale/timescaledb-toolkit#373]
#### Description ####
An implementation of `approx_count` originally proposed in #6. The proposed implementation would sit atop a new aggregate (`count_agg`?) that uses the Count-Min Sketch data structure. Interrogating the count aggregate via `approx_count` would give an estimated frequency. 

The Count-Min Sketch is an array of counters parameterized by the number of rows `d` in the array and by the number of buckets in a row `w`. If we take `w = 2/ε` and `d = ln(1/δ)`, then we have that the estimated frequency of a given item has error at most `εN` with probability at least `1 − δ`, where `N` is the number of elements present in the data stream. I think we could make the `ε` and `δ` optional parameters to `count_agg` rather than hard-coding in a level of performance guarantees (and space complexity) for all sketches.

#### Proposed API ####
To get the count aggregate use
```sql
SELECT count_agg(value, 0.01, 0.01) FROM tbl;
```
and to query the estimated count of a given item "foo" in the table use
```sql
SELECT approx_count(count_agg(value), "foo") FROM tbl;
```
I think as a first pass I'll just get this to work on `text` columns before exploring supporting a broader number of types.

#### Alternatives ####
Could use a Count-Sketch (which does a median calculation instead of a min). 

From pg. 16 of http://dimacs.rutgers.edu/~graham/

> **1.3.2.1 Refining Count-Sketch and Count-Min Sketch guarantees**
We have seen that the Count-Sketch and Count-Min sketch both allow f (i) to
be approximated via somewhat similar data structures. They differ in provid-
ing distinct space/accuracy trade-offs: the Count sketch gives ε√F2 error with
O(1/ε2) space, whereas the Count-Min sketch gives εN error with O(1/ε)
space. In general, these bounds cannot be compared: there exist some fre-
quency vectors where (given the same overall space budget) one guarantee
is preferable, and others where the other dominates. Indeed, various experi-
mental studies have shown that over real data it is not always clear which is
preferable [23].

There are fewer hash functions to keep up with in a Count-Min sketch, so I'm inclined to try it first.

EDIT: I think it might also be worth seeing how well we can do using the SpaceSaving algorithm/data structure underlying`freq_agg`. I think it would make it much easier on users if we could consolidate into one aggregate here instead of offering both a `freq_agg` and a `count_agg` that support different functions. Could use `approx_freq` instead of `approx_count` for consistency if we go that route.

#### Roadmap ####
- [ ] Implement a Count-Min Sketch data structure #388 
- [ ] Define the `count_agg` aggregate
- [ ] Implement the `approx_count` API on top of `count_agg`

**Comment by rtwalker** [comment]
Semi-documenting (until I have a better place to put it) that is this is a useful video to watch for someone implementing their first aggregate: https://www.youtube.com/watch?v=-lFnvYBLgsU
