### ISSUE TITLE
Epic : Release Automation Phase 2

### ISSUE THREAD

**Issue by thatzopoulos** [timescale/timescaledb-toolkit#575]
The main goal for this phase is to do automated updating tests using the published binaries for the previous releases instead of building the previous releases from source so that 1) we test what we ship 2) testing env is simplified 3) testing speed is improved. This has several steps. 

Priority:
- [x] Update CI build to use old published binaries for update testing rather than rebuilding them all. This will be necessary when we upgrade to pgx 0.5 unless we want to require 3 pgx installations (https://github.com/timescale/timescaledb-toolkit/pull/554)
- [x] Add update-tester tests for Time Vector (https://github.com/timescale/timescaledb-toolkit/pull/558)

Nice to have:
- [x] Update code so that it sets a new DB per test file (https://github.com/timescale/timescaledb-toolkit/pull/580)
- [x] Automatically set the timezone to UTC (https://github.com/timescale/timescaledb-toolkit/pull/566)
- [x] Update so that num_errors reports the amount of failed tests when exiting (https://github.com/timescale/timescaledb-toolkit/pull/587)
- [x] Look into replacing the writeln! calls with eprintln! calls in the update-tester (https://github.com/timescale/timescaledb-toolkit/pull/587)
- [x] Remove ROOT_DIR from subcommands that require it (https://github.com/timescale/timescaledb-toolkit/pull/577)
